#Builds and tests in release config
trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables: #Path to folder with .sln
  solution: Project Code

stages: 
- stage: build
  jobs:
  - job: build
    
    steps:
    - task: UseDotNet@2
      displayName: Dotnet SDK 5
      inputs:
        packageType: 'sdk'
        version: '5.x
    
    - script: dotnet build --configuration Release
      displayName: dotnet build
      workingDirectory: $(solution)

    - script: dotnet test --configuration Release
      displayName: dotnet test
      workingDirectory: $(solution)