
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
-stage: sonar
jobs:
-jobs: sonar

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'P1 Scanner'
    organization: '210726-wvu-net-ext'
    scannerMode: 'MSBuild'
    projectKey: '210726-wvu-net-ext_P1-Emery-Hart'
    projectName: 'P1-Emery-Hart'

   - script: dotnet build --configuration Release
      displayName: dotnet build
      workingDirectory: $(solution)